# Generated by Django 5.1.4 on 2024-12-27 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_remove_affiliatelinks_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelinks',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatelinks',
            name='date_listed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
