# Generated by Django 5.1.4 on 2024-12-27 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_affiliatelinks_author_id_affiliatelinks_date_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatelinks',
            name='id',
        ),
        migrations.AlterField(
            model_name='affiliatelinks',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
