# Generated by Django 5.1.4 on 2024-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_remove_affiliatelinks_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelinks',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
